#!/bin/sh
cat << __EOC__
$ ./configure  '--with-readline=/usr/include/readline' '--disable-conio' '--bindir=/usr/bin' '--sbindir=/usr/sbin' '--with-scriptdir=/etc/bacula/scripts' '--with-working-dir=/var/lib/bacula' '--with-logdir=/var/log' '--enable-smartalloc' '--with-postgresql' '--with-archivedir=/mnt/backup' '--with-job-email=suporte@fametec.com.br' '--with-hostname='

Configuration on Sat Sep 28 14:25:04 UTC 2019:

   Host:		     x86_64-pc-linux-gnu -- debian 10.1
   Bacula version:	     Bacula 9.4.4 (28 May 2019)
   Source code location:     .
   Install binaries:	     /usr/sbin
   Install libraries:	     /usr/lib
   Install config files:     /etc/bacula
   Scripts directory:	     /etc/bacula/scripts
   Archive directory:	     /mnt/backup
   Working directory:	     /var/lib/bacula
   PID directory:	     /var/run
   Subsys directory:	     /var/run/subsys
   Man directory:	     /usr/share/man
   Data directory:	     /usr/share
   Plugin directory:	     /usr/lib
   C Compiler:		     gcc 8.3.0-6)
   C++ Compiler:	     /usr/bin/g++ 8.3.0-6)
   Compiler flags:	      -g -O2 -Wall -x c++ -fno-strict-aliasing -fno-exceptions -fno-rtti
   Linker flags:	      
   Libraries:		     -lpthread -ldl -ldl 
   Statically Linked Tools:  no
   Statically Linked FD:     no
   Statically Linked SD:     no
   Statically Linked DIR:    no
   Statically Linked CONS:   no
   Database backends:	     PostgreSQL
   Database port:	      
   Database name:	     bacula
   Database user:	     bacula
   Database SSL options:     

   Job Output Email:	     suporte@fametec.com.br
   Traceback Email:	     root@localhost
   SMTP Host Address:	     localhost

   Director Port:	     9101
   File daemon Port:	     9102
   Storage daemon Port:      9103

   Director User:	     
   Director Group:	     
   Storage Daemon User:      
   Storage DaemonGroup:      
   File Daemon User:	     
   File Daemon Group:	     

   Large file support:	     yes
   Bacula conio support:     no -lreadline -lhistory -ltinfo
   readline support:	     yes 
   TCP Wrappers support:     no 
   TLS support: 	     yes
   Encryption support:	     yes
   ZLIB support:	     yes
   LZO support: 	     yes
   enable-smartalloc:	     yes
   enable-lockmgr:	     no
   bat support: 	     no
   client-only: 	     no
   build-dird:		     yes
   build-stored:	     yes
   Plugin support:	     yes
   AFS support: 	     no
   ACL support: 	     yes
   XATTR support:	     yes
   systemd support:	     no 
   Batch insert enabled:     PostgreSQL

  
__EOC__
