version: '3.1'
#
services:

  base: 
    build: bacula-base/
    image: eftechcombr/bacula:13.0.3-base
#    
  db:
    build: bacula-catalog/
    image: eftechcombr/bacula:13.0.3-catalog
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: bacula
      POSTGRES_USER: bacula
      POSTGRES_DB: bacula
    # volumes:
    #   - pgdata:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432
#
  bacula-dir:
    build: bacula-dir/
    image: eftechcombr/bacula:13.0.3-director
    restart: unless-stopped
    volumes:
      - ./etc:/opt/bacula/etc:ro
    depends_on: 
      - db      
    ports:
      - 9101:9101
#
  bacula-sd:
    build: bacula-sd/
    image: eftechcombr/bacula:13.0.3-storage
    restart: unless-stopped
    depends_on:
      - bacula-dir
      - db
    volumes:
      - ./etc:/opt/bacula/etc:ro
    ports:
      - 9103:9103
#
  bacula-fd:
    build: bacula-fd/
    image: eftechcombr/bacula:13.0.3-client
    restart: unless-stopped
    depends_on:
      - bacula-sd
      - bacula-dir
      - db
    volumes:
      - ./etc:/opt/bacula/etc:ro
    ports:
      - 9102:9102
#
  # bacula-fd-git:
  #   build: 
  #     context: bacula-fd/
  #     dockerfile: Dockerfile-git
  #   image: eftechcombr/bacula:13.0.3-client-git
  #   restart: unless-stopped
  #   environment: 
  #     USERNAME: <username>
  #     TOKEN: <token>
  #     ORG: <org>
  #   volumes:
  #     - ./etc:/opt/bacula/etc:ro
  #   ports:
  #     - 9202:9102


  # bacula-fd-s3fs:
  #   build: 
  #     context: bacula-fd/
  #     dockerfile: Dockerfile-s3fs
  #   image: eftechcombr/bacula:13.0.3-client-s3fs
  #   restart: unless-stopped
  #   cap_add:
  #     - SYS_ADMIN
  #   # security_opt:
  #   #   - 'apparmor:unconfined'
  #   devices:
  #     - /dev/fuse
  #   # volumes:
  #   #   - bucket:/opt/s3fs/bucket
  #   environment:
  #     AWS_S3_BUCKET: ${AWS_S3_BUCKET}
  #     AWS_S3_ACCESS_KEY_ID: ${AWS_S3_ACCESS_KEY_ID}
  #     AWS_S3_SECRET_ACCESS_KEY: ${AWS_S3_SECRET_ACCESS_KEY} 
  #   volumes:
  #     - ./etc:/opt/bacula/etc:ro
  #   ports:
  #     - 9112:9102

#
  baculum-api:
    build: baculum-api/
    image: eftechcombr/baculum:11.0.6-api
    restart: unless-stopped
    depends_on: 
      - db
      - bacula-dir
    volumes:
      - ./etc/bconsole.conf:/opt/bacula/etc/bconsole.conf:ro
      - ./etc/baculum:/etc/baculum:rw
    ports:
      - 9096:9096
#
  baculum-web:
    build: baculum-web/
    image: eftechcombr/baculum:11.0.6-web
    restart: unless-stopped
    depends_on: 
      - baculum-api
    volumes:
      - ./etc/bconsole.conf:/opt/bacula/etc/bconsole.conf:ro
      - ./etc/baculum:/etc/baculum:rw
    ports:
      - 9095:9095
# 
#volumes: 
#  pgdata:
#
#  gmail:
#    image: eftechcombr/postfix:gmail
#    restart: unless-stopped
#    depends_on:
#      - bacula-dir
#    # ports:
#    #  - 30025:25
#    environment:
#      GMAIL_USER: xxxxxxxx
#      GMAIL_PASS: xxxxxxxx
#
#  smtp2tg:
#    image: b3vis/docker-smtp2tg
#    restart: unless-stopped
#    volumes:
#      - ./etc/smtp2tg.toml:/config/smtp2tg.toml:ro
#    #    ports:
#    #  - "31025:25"
#    depends_on:
#      - bacula-dir
#
# 
# volumes: 
#   pgdata:
#   bucket:
