---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bacula-dir
  name: bacula-dir
  namespace: backup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bacula-dir
  strategy: {}
  template:
    metadata:
      labels:
        app: bacula-dir
    spec:
      containers:
      - image: docker.io/eftechcombr/bacula:13.0.1-director
        name: bacula-dir
        ports:
        - containerPort: 9101
        volumeMounts:
        - name: bacula-dir
          mountPath: "/opt/bacula/etc/bacula-dir.conf"
          subPath: bacula-dir.conf
          readOnly: true
        - name: bconsole
          mountPath: "/opt/bacula/etc/bconsole.conf"
          subPath: bconsole.conf
          readOnly: true
        resources: {}
      volumes:
      - name: bacula-dir
        configMap:
          name: bacula-dir
      - name: bconsole
        configMap: 
          name: bconsole
status: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bacula-sd
  name: bacula-sd
  namespace: backup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bacula-sd
  strategy: {}
  template:
    metadata:
      labels:
        app: bacula-sd
    spec:
      containers:
      - image: docker.io/eftechcombr/bacula:13.0.1-storage
        name: bacula-sd
        ports:
        - containerPort: 9103
        volumeMounts:
        - name: bacula-sd
          mountPath: "/opt/bacula/etc"
          readOnly: true
        resources: {}
      volumes:
      - name: bacula-sd
        configMap:
          name: bacula-sd
status: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bacula-fd
  name: bacula-fd
  namespace: backup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bacula-fd
  strategy: {}
  template:
    metadata:
      labels:
        app: bacula-fd
    spec:
      containers:
      - image: docker.io/eftechcombr/bacula:13.0.1-client
        name: bacula-fd
        ports:
        - containerPort: 9102
        volumeMounts:
        - name: bacula-fd
          mountPath: "/opt/bacula/etc"
          readOnly: true
        resources: {}
      volumes:
      - name: bacula-fd
        configMap:
          name: bacula-fd
status: {}


---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: baculum-api
  name: baculum-api
  namespace: backup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: baculum-api
  strategy: {}
  template:
    metadata:
      labels:
        app: baculum-api
    spec:
      initContainers:
      - image: docker.io/eftechcombr/baculum:11.0.6-api
        name: baculum-init
        volumeMounts:
        - name: baculum-api
          mountPath: "/tmp/baculum/Config-api-apache"
          readOnly: true
        - name: etc-baculum
          mountPath: "/etc/baculum"
        command:
          - bash
          - -c
          - "cp -Rf /tmp/baculum/Config-api-apache /etc/baculum && chmod a+w /etc/baculum/Config-api-apache"
      containers:
      - image: docker.io/eftechcombr/baculum:11.0.6-api
        name: baculum-api
        ports:
        - containerPort: 9096
        volumeMounts:
        - name: etc-baculum
          mountPath: "/etc/baculum"
        - name: bconsole
          mountPath: "/opt/bacula/etc/bconsole.conf"
          subPath: bconsole.conf
          readOnly: true 
        - name: bacula-dir
          mountPath: "/opt/bacula/etc/bacula-dir.conf"
          subPath: bacula-dir.conf
          readOnly: true 
        - name: bacula-fd
          mountPath: "/opt/bacula/etc/bacula-fd.conf"
          subPath: bacula-fd.conf 
          readOnly: true
        - name: bacula-sd
          mountPath: "/opt/bacula/etc/bacula-sd.conf"
          subPath: bacula-sd.conf 
          readOnly: true
        resources: {}
      volumes:
      - name: bacula-sd
        configMap:
          name: bacula-sd
      - name: bacula-dir
        configMap:
          name: bacula-dir
      - name: bacula-fd
        configMap:
          name: bacula-fd
      - name: baculum-api
        configMap:
          name: baculum-api
      - name: bconsole
        configMap: 
          name: bconsole
      - name: etc-baculum
        emptyDir: {}
status: {}



---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: baculum-web
  name: baculum-web
  namespace: backup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: baculum-web
  strategy: {}
  template:
    metadata:
      labels:
        app: baculum-web
    spec:
      containers:
      - image: docker.io/eftechcombr/baculum:11.0.6-web
        name: baculum-web
        ports:
        - containerPort: 9095
        volumeMounts:
        - name: baculum-web
          mountPath: "/etc/baculum/Config-web-apache"
          readOnly: true
        resources: {}
      volumes:
      - name: baculum-web
        configMap:
          name: baculum-web

status: {}
