---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bacula-dir
  name: bacula-dir
  namespace: backup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bacula-dir
  strategy: {}
  template:
    metadata:
      labels:
        app: bacula-dir
    spec:
      containers:
      - image: docker.io/eftechcombr/bacula:13.0.1-director
        name: bacula
        ports:
        - containerPort: 9101
        volumeMounts:
        - name: bacula-dir
          mountPath: "/opt/bacula/etc"
          readOnly: true
        resources: {}
      volumes:
      - name: bacula-dir
        configMap:
          name: bacula-dir

status: {}

