
###############################################################################
# 
###############################################################################

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bacula-dir
  name: bacula-dir
  namespace: backup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bacula-dir
  strategy: {}
  template:
    metadata:
      labels:
        app: bacula-dir
    spec:
      initContainers:
      - image: docker.io/eftechcombr/bacula:13.0.1-director
        name: bacula-init
        volumeMounts: 
        - name: bacula-dir
          mountPath: "/tmp/bacula/bacula-dir.conf"
          subPath: bacula-dir.conf
          readOnly: true
        - name: bconsole
          mountPath: "/tmp/bacula/bconsole.conf"
          subPath: bconsole.conf
          readOnly: true
        - name: bacula-etc
          mmountPath: "/opt/bacula/etc"
        command: 
        - bash
        - -c 
        - "if [ ! -z /opt/bacula/etc/bacula-dir.conf ]; then cp -Rf /tmp/bacula/* /opt/bacula/etc/; fi"
      containers:
      - image: docker.io/eftechcombr/bacula:13.0.1-director
        name: bacula-dir
        ports:
        - containerPort: 9101
        volumeMounts:
        - name: bacula-etc
          mountPath: "/opt/bacula/etc"
        resources: {}
      volumes:
      - name: bacula-dir
        configMap:
          name: bacula-dir
      - name: bconsole
        configMap: 
          name: bconsole
      - name: bacula-etc
        emptyDir: {}
status: {}


###############################################################################
# 
###############################################################################
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bacula-dir
  name: bacula-dir
  namespace: backup
spec:
  ports:
  - port: 9101
    protocol: TCP
    targetPort: 9101
  selector:
    app: bacula-dir
status:
  loadBalancer: {}
