
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bacula-dir
  name: bacula-dir
  namespace: backup
spec:
  ports:
  - port: 9101
    protocol: TCP
    targetPort: 9101
  selector:
    app: bacula-dir
status:
  loadBalancer: {}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bacula-sd
  name: bacula-sd
  namespace: backup
spec:
  ports:
  - port: 9103
    protocol: TCP
    targetPort: 9103
  selector:
    app: bacula-sd
status:
  loadBalancer: {}