
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bacula-dir
  name: bacula-dir
  namespace: backup
spec:
  ports:
  - port: 9101
    protocol: TCP
    targetPort: 9101
  selector:
    app: bacula-dir
status:
  loadBalancer: {}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bacula-sd
  name: bacula-sd
  namespace: backup
spec:
  ports:
  - port: 9103
    protocol: TCP
    targetPort: 9103
  selector:
    app: bacula-sd
status:
  loadBalancer: {}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bacula-fd
  name: bacula-fd
  namespace: backup
spec:
  ports:
  - port: 9102
    protocol: TCP
    targetPort: 9102
  selector:
    app: bacula-fd
status:
  loadBalancer: {}



---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: baculum-api
  name: baculum-api
  namespace: backup
spec:
  ports:
  - port: 9096
    protocol: TCP
    targetPort: 9096
  selector:
    app: baculum-api
status:
  loadBalancer: {}



---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: baculum-web
  name: baculum-web
  namespace: backup
spec:
  ports:
  - port: 9095
    protocol: TCP
    targetPort: 9095
  selector:
    app: baculum-web
status:
  loadBalancer: {}  