#!/bin/sh
#
# Copyright (C) 2000-2018 Kern Sibbald
# License: BSD 2-Clause; see file LICENSE-FOSS
#
#  Make the stupid bacula.def file so that we don't have to do it
#    manually
#
#  Kern Sibbald, June 2007
#

TOPDIR=`(cd ../../..;pwd)`
TOPDIR=${DEPKGS:-${TOPDIR}}
NM=x86_64-w64-mingw32-nm
 
echo "LIBRARY bacula.dll"
echo "EXPORTS"
echo " "

cd obj64
# remove "static" objects before running
rm -f parse_conf.* res.*

for i in `ls *.o | grep -v -e parse_conf.o -e res.o`; do \
   echo "; $i"; \
   ${NM} $i | grep -e "^[0-9a-f]* T _" -e "^[0-9a-f]* T b_reg" -e "^[0-9a-f]* T fnmatch" | cut -c20- ; \
   echo " "; \
done

DATA="console_command b_plugin_list plugin_bopen plugin_bclose plugin_bwrite plugin_bread plugin_blseek exepath version dist_name"

for i in ${DATA}; do \
   echo "$i DATA"; \
done
